INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mobile.twitter.com:443
DEBUG:urllib3.connectionpool:https://mobile.twitter.com:443 "GET /pinkfloyd HTTP/1.1" 200 8108
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mobile.twitter.com:443
DEBUG:urllib3.connectionpool:https://mobile.twitter.com:443 "GET /pinkfloyd HTTP/1.1" 200 8109
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mobile.twitter.com:443
DEBUG:urllib3.connectionpool:https://mobile.twitter.com:443 "GET /pinkfloyd HTTP/1.1" 200 8109
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mobile.twitter.com:443
DEBUG:urllib3.connectionpool:https://mobile.twitter.com:443 "GET /pinkfloyd/status/1325772237341945858 HTTP/1.1" 200 5097
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): mobile.twitter.com:443
DEBUG:urllib3.connectionpool:https://mobile.twitter.com:443 "GET /pinkfloyd/status/1325772237341945858 HTTP/1.1" 200 5099
INFO:root:handle got called with the following parameters:[(<Analysers.Handlers.NewsFilterSocialMediaHandler object at 0x07D6C1D0>, <DataLayer.DataSetEntry.TwitterDataSetEntryUnlabeled object at 0x081D9C10>, <Analysers.Models.AnalysisResult object at 0x07D6C1F0>)] [{}]
INFO:root:A query will be executed against the database
ERROR:ServerApi:Exception on / [POST]
Traceback (most recent call last):
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\flask_restful\__init__.py", line 468, in wrapper
    resp = resource(*args, **kwargs)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\flask\views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\flask_restful\__init__.py", line 583, in dispatch_request
    resp = meth(*args, **kwargs)
  File "C:/Users/bianc/Desktop/ASET/FakeNews/ServerComponent/ServerApi.py", line 21, in post
    return {"response": self.myService.analyseRequest(args['html'], args['url'])}
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\Services.py", line 15, in analyseRequest
    result = self.analyseTwitterPost(html, url)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\Services.py", line 39, in analyseTwitterPost
    handler.handle(post, result)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 290, in advising_function_wrapper
    advice = advisor.throw(*sys.exc_info())
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\Utils\LoggingAspect.py", line 10, in logging_aspect
    function_call_result = yield
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 288, in advising_function_wrapper
    result = cutpoint_function(*args, **kwargs)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\Analysers\Handlers.py", line 69, in handle
    fit_data, fit_labels = adapter.convert_to_training_datasets()
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\DataLayer\DataSetAdapter.py", line 24, in convert_to_training_datasets
    db_entries = self.provide_dataset_entries()
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 290, in advising_function_wrapper
    advice = advisor.throw(*sys.exc_info())
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\DataLayer\aspects.py", line 8, in my_decorator_exit_db
    raw_data = yield
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 288, in advising_function_wrapper
    result = cutpoint_function(*args, **kwargs)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\DataLayer\DataSetAdapter.py", line 15, in provide_dataset_entries
    raw_data = self.data_set_provider.get_data_set_entries()
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\DataLayer\DataSetProvider.py", line 20, in get_data_set_entries
    return DatabaseOperations.get_all()
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 290, in advising_function_wrapper
    advice = advisor.throw(*sys.exc_info())
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\Utils\DatabaseAspect.py", line 12, in query_aspect
    function_call_result = yield
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\venv\lib\site-packages\aspectlib\__init__.py", line 288, in advising_function_wrapper
    result = cutpoint_function(*args, **kwargs)
  File "C:\Users\bianc\Desktop\ASET\FakeNews\ServerComponent\DataLayer\DatabaseOperations.py", line 16, in get_all
    result = conn.execute("Select * FROM SocialMediaPosts")
sqlite3.ProgrammingError: SQLite objects created in a thread can only be used in that same thread. The object was created in thread id 7212 and this is thread id 7440.
INFO:werkzeug:127.0.0.1 - - [12/Dec/2020 17:23:42] "[35m[1mPOST / HTTP/1.1[0m" 500 -
